# Generated by Django 4.1.3 on 2022-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('dept', models.CharField(blank=True, max_length=120, null=True)),
                ('post', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField()),
                ('leave', models.IntegerField()),
                ('on_leave', models.BooleanField(default=False)),
            ],
        ),
    ]
