# Generated by Django 4.1.3 on 2022-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_employee_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
